In [1]:
print("Hello World")

Hello World

In [19]:
include("parser.jl")

r, c, b, m, t = readfile("Instances/gap1.txt",2);

In [3]:
variables = ["r", "c", "b", "m", "t"]
values = [r, c, b, m, t]

for i in 1:length(variables)
    println("$(variables[i]) : $(values[i])")
end

r : Any[19 8 16 19 11 25 20 5 23 11 20 8 18 5 12 13 12 6 11 8 8 23 17 9 18 5 6 23 9 24 24 19 23 13 10 5 11 24 10 22; 9 22 15 17 7 24 19 19 11 6 17 18 9 23 14 20 7 17 23 7 15 8 16 16 9 25 6 5 5 25 7 18 5 18 6 10 8 10 16 18; 20 22 15 23 25 25 6 5 14 23 11 5 20 6 5 7 8 9 17 6 8 13 22 19 5 18 13 20 16 12 23 25 11 19 8 21 9 22 8 22; 6 7 15 8 11 16 17 14 7 8 20 14 23 13 11 25 5 25 18 5 8 20 9 9 25 23 6 15 20 24 7 19 7 6 7 12 5 10 17 12; 25 12 10 20 12 24 20 14 21 5 20 9 12 13 22 23 14 14 14 25 21 5 8 11 19 14 17 15 25 13 14 16 21 8 6 19 7 6 22 20; 10 16 19 14 9 18 15 10 19 6 10 11 7 23 24 14 12 5 25 16 13 8 13 25 9 24 15 6 11 24 14 9 24 6 18 21 20 21 10 10; 6 8 20 24 9 24 24 10 21 20 12 11 8 24 5 8 10 25 5 6 9 8 20 16 14 7 25 11 10 24 17 23 13 16 9 8 5 15 21 23; 12 5 20 13 21 15 11 15 22 20 13 8 18 20 5 20 14 12 22 15 19 7 22 16 15 15 23 19 20 16 10 20 20 11 14 15 12 22 20 22; 22 24 10 12 19 20 14 16 10 11 9 15 17 25 5 14 21 24 24 19 15 10 24 9 14 24 15 16 19 14 14 22 13 17 10 11 6 16 12 9; 

In [4]:
# r : quantité de ressources consommées par tâche (matrix)
r

10×40 Matrix{Any}:
 19   8  16  19  11  25  20   5  23  …  19  23  13  10   5  11  24  10  22
  9  22  15  17   7  24  19  19  11     18   5  18   6  10   8  10  16  18
 20  22  15  23  25  25   6   5  14     25  11  19   8  21   9  22   8  22
  6   7  15   8  11  16  17  14   7     19   7   6   7  12   5  10  17  12
 25  12  10  20  12  24  20  14  21     16  21   8   6  19   7   6  22  20
 10  16  19  14   9  18  15  10  19  …   9  24   6  18  21  20  21  10  10
  6   8  20  24   9  24  24  10  21     23  13  16   9   8   5  15  21  23
 12   5  20  13  21  15  11  15  22     20  20  11  14  15  12  22  20  22
 22  24  10  12  19  20  14  16  10     22  13  17  10  11   6  16  12   9
  7   8  12  24  12  14   7  11  19     10  19  14  25  18  21  21   9  21

In [5]:
# c : gain par tâche pour chaque agent (matrix)
c

10×40 Matrix{Any}:
 24  18  17  19  19  24  20  23  15  …  22  20  21  21  16  24  16  20  24
 16  16  23  21  25  20  16  25  20     21  17  22  23  25  22  17  16  19
 25  19  20  25  20  20  24  20  24     21  24  17  20  19  20  18  22  20
 21  24  18  18  17  17  20  17  21     21  17  18  22  17  16  21  18  19
 24  16  19  15  23  22  17  23  25     20  22  25  25  20  25  22  15  22
 19  25  18  18  24  22  16  22  21  …  16  21  18  20  16  16  21  16  16
 18  16  24  18  17  20  19  24  17     24  19  15  22  20  25  20  22  17
 25  24  21  15  20  22  17  17  16     21  18  21  15  20  18  18  16  20
 15  18  18  17  21  23  24  24  18     25  24  24  21  16  23  25  24  22
 20  24  18  21  20  23  25  17  20     20  23  23  16  25  21  19  22  18

In [6]:
# b : quantité de ressource de l'agent i (vect)
b

10-element Vector{Any}:
 45
 44
 46
 42
 49
 46
 45
 51
 49
 49

In [7]:
# m : nombre d'agents (int) --> nombre de lignes
m

10

In [8]:
# t : nombre de tâches (int) --> nombre de colonnes
t

40

### Heuristique gloutonne

In [ ]:
function greedy(file, instance)

    r, c, b, m, t = readfile(file,instance);

    current_load = fill(0, m)
    assignment = fill(0, t)
    cost = 0

    end_condition = fill(100, m, t)

    while r != end_condition
        # Booléen pour sortir de la boucle si rien ne se passe
        feasibility = false
        for i in 1:m
            # Si la tâche qui nécessite le moins de ressources satisfait la contrainte
            min = minimum(r[i, :])
            amin = argmin(r[i, :])
            if current_load[i] + min <= b[i]
                feasibility = true
                # On assigne la nouvelle tâche à l'agent
                assignment[amin] = i
                # On augmente sa charge
                current_load[i] += min
                # On ajoute le coût associée
                cost += c[i, amin]
                # On enlève la tâche des tâches à assigner
                r[:, amin] .= 100
            end
        end
        if feasibility == false
            # Pas de solution, on sort de la boucle
            print("Pas de solution.")
            break
        end

    end

Pas de solution.

In [10]:
assignment

40-element Vector{Int64}:
 10
  8
  7
  8
  2
  8
  3
  1
  4
  5
  ⋮
  6
  2
  6
  5
  1
  9
  5
  3
  9

In [18]:
cost

797

### Heuristique gloutonne

In [11]:
ratio = c./r

10×40 Matrix{Float64}:
 0.24  0.18  0.17  0.19  0.19  0.24  …  0.21  0.16  0.24  0.16  0.2   0.24
 0.16  0.16  0.23  0.21  0.25  0.2      0.23  0.25  0.22  0.17  0.16  0.19
 0.25  0.19  0.2   0.25  0.2   0.2      0.2   0.19  0.2   0.18  0.22  0.2
 0.21  0.24  0.18  0.18  0.17  0.17     0.22  0.17  0.16  0.21  0.18  0.19
 0.24  0.16  0.19  0.15  0.23  0.22     0.25  0.2   0.25  0.22  0.15  0.22
 0.19  0.25  0.18  0.18  0.24  0.22  …  0.2   0.16  0.16  0.21  0.16  0.16
 0.18  0.16  0.24  0.18  0.17  0.2      0.22  0.2   0.25  0.2   0.22  0.17
 0.25  0.24  0.21  0.15  0.2   0.22     0.15  0.2   0.18  0.18  0.16  0.2
 0.15  0.18  0.18  0.17  0.21  0.23     0.21  0.16  0.23  0.25  0.24  0.22
 0.2   0.24  0.18  0.21  0.2   0.23     0.16  0.25  0.21  0.19  0.22  0.18

In [12]:
argmax(ratio)

CartesianIndex(3, 1)

In [13]:
current_ressource = zeros(m)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [14]:
current_ressource[1] < b[1]

true

In [15]:
ratio[10,:]

40-element Vector{Float64}:
 0.2
 0.24
 0.18
 0.21
 0.2
 0.23
 0.25
 0.17
 0.2
 0.15
 ⋮
 0.2
 0.23
 0.23
 0.16
 0.25
 0.21
 0.19
 0.22
 0.18

In [16]:
ratio

10×40 Matrix{Float64}:
 0.24  0.18  0.17  0.19  0.19  0.24  …  0.21  0.16  0.24  0.16  0.2   0.24
 0.16  0.16  0.23  0.21  0.25  0.2      0.23  0.25  0.22  0.17  0.16  0.19
 0.25  0.19  0.2   0.25  0.2   0.2      0.2   0.19  0.2   0.18  0.22  0.2
 0.21  0.24  0.18  0.18  0.17  0.17     0.22  0.17  0.16  0.21  0.18  0.19
 0.24  0.16  0.19  0.15  0.23  0.22     0.25  0.2   0.25  0.22  0.15  0.22
 0.19  0.25  0.18  0.18  0.24  0.22  …  0.2   0.16  0.16  0.21  0.16  0.16
 0.18  0.16  0.24  0.18  0.17  0.2      0.22  0.2   0.25  0.2   0.22  0.17
 0.25  0.24  0.21  0.15  0.2   0.22     0.15  0.2   0.18  0.18  0.16  0.2
 0.15  0.18  0.18  0.17  0.21  0.23     0.21  0.16  0.23  0.25  0.24  0.22
 0.2   0.24  0.18  0.21  0.2   0.23     0.16  0.25  0.21  0.19  0.22  0.18