In [13]:
print("Hello World")

Hello World

In [14]:
include("parser.jl")

r, c, b, m, t = readfile("Instances/gap1.txt",2);

In [15]:
variables = ["r", "c", "b", "m", "t"]
values = [r, c, b, m, t]

for i in 1:length(variables)
    println("$(variables[i]) : $(values[i])")
end

r : Any[23 10 15 13 17 10 13 6 9 21 20 7 9 25 8; 17 13 8 23 11 18 7 22 13 5 24 24 15 10 22; 22 17 22 23 20 11 17 25 23 9 22 20 15 9 25; 5 19 25 16 15 10 18 9 11 20 7 21 15 8 25; 22 9 10 23 19 21 17 15 15 17 25 19 10 9 21]
c : Any[22 21 16 17 21 15 17 22 22 25 18 20 24 15 22; 23 24 19 15 16 21 15 25 16 21 20 19 16 23 20; 21 20 21 25 21 20 21 19 17 16 25 19 15 15 15; 17 21 25 25 23 22 20 19 20 25 15 20 21 25 23; 15 25 23 19 17 17 25 24 24 17 24 19 18 19 16]
b : Any[32, 37, 44, 35, 40]
m : 5
t : 15


In [16]:
# r : quantité de ressources consommées par tâche (matrix)
r

5×15 Matrix{Any}:
 23  10  15  13  17  10  13   6   9  21  20   7   9  25   8
 17  13   8  23  11  18   7  22  13   5  24  24  15  10  22
 22  17  22  23  20  11  17  25  23   9  22  20  15   9  25
  5  19  25  16  15  10  18   9  11  20   7  21  15   8  25
 22   9  10  23  19  21  17  15  15  17  25  19  10   9  21

In [17]:
# c : gain par tâche pour chaque agent (matrix)
c

5×15 Matrix{Any}:
 22  21  16  17  21  15  17  22  22  25  18  20  24  15  22
 23  24  19  15  16  21  15  25  16  21  20  19  16  23  20
 21  20  21  25  21  20  21  19  17  16  25  19  15  15  15
 17  21  25  25  23  22  20  19  20  25  15  20  21  25  23
 15  25  23  19  17  17  25  24  24  17  24  19  18  19  16

In [18]:
# b : quantité de ressource de l'agent i (vect)
b

5-element Vector{Any}:
 32
 37
 44
 35
 40

In [19]:
# m : nombre d'agents (int) --> nombre de lignes
m

5

In [20]:
# t : nombre de tâches (int) --> nombre de colonnes
t

15

### Heuristique gloutonne

In [21]:
function greedy(file, instance)

    r, c, b, m, t = readfile(file, instance);

    current_load = fill(0, m)
    assignment = fill(0, t)
    cost = 0

    end_condition = fill(100, m, t)

    while r != end_condition
        # Booléen pour sortir de la boucle si rien ne se passe
        feasibility = false
        for i in 1:m
            # Si la tâche qui nécessite le moins de ressources satisfait la contrainte
            min = minimum(r[i, :])
            amin = argmin(r[i, :])
            if current_load[i] + min <= b[i]
                feasibility = true
                # On assigne la nouvelle tâche à l'agent
                assignment[amin] = i
                # On augmente sa charge
                current_load[i] += min
                # On ajoute le coût associée
                cost += c[i, amin]
                # On enlève la tâche des tâches à assigner
                r[:, amin] .= 100
            end
        end
        if feasibility == false
            # Pas de solution, on sort de la boucle
            # print("Pas de solution.")
            # break
            return 0
        end

    end
    # println(assignment)
    # println(cost)
    return (assignment, cost)
end

greedy (generic function with 1 method)

In [22]:
assignment, cost = greedy("Instances/gap2.txt", 2)

([3, 1, 1, 2, 5, 2, 3, 2, 5, 3, 2, 4, 4, 4, 1, 3, 5, 4, 1, 5], 358)

In [55]:
cal_cost([3, 1, 1, 2, 5, 2, 3, 2, 5, 3, 2, 4, 4, 4, 1, 3, 5, 4, 1, 5], "Instances/gap2.txt", 2)

358

### Create CSV

In [23]:
using DataFrames
using CSV

In [24]:
files = readdir("Instances")

16-element Vector{String}:
 "gap1.txt"
 "gap10.txt"
 "gap11.txt"
 "gap12.txt"
 "gap2.txt"
 "gap3.txt"
 "gap4.txt"
 "gap5.txt"
 "gap6.txt"
 "gap7.txt"
 "gap8.txt"
 "gap9.txt"
 "gapa.txt"
 "gapb.txt"
 "gapc.txt"
 "gapd.txt"

In [25]:
greedy("Instances/gap1.txt", 0)

([1, 2, 3, 4, 1, 4, 4, 3, 5, 2, 2, 5, 5, 1, 3], 294)

In [26]:
df = DataFrame(id = Int[], file = String[], instance = Int[], performance = Int[])

0×4 DataFrame
 Row │ id     file    instance  performance 
     │ Int64  String  Int64     Int64       
─────┴──────────────────────────────────────

In [27]:
push!(df, (1, "test", 1, 10))

1×4 DataFrame
 Row │ id     file    instance  performance 
     │ Int64  String  Int64     Int64       
─────┼──────────────────────────────────────
   1 │     1  test           1           10

In [ ]:
df = DataFrame(id = Int[], file = String[], instance = Int[], greedy_worker = Int[])
id = 0

for file in files
    path = "Instances/"*file
    nb_instances = parse(Int, readline(path))
    for instance in 0:nb_instances-1
        greedy_worker = greedy(path, instance)
        push!(df, (id, path, instance, greedy_worker))
        id += 1
    end
end

BoundsError: BoundsError: attempt to access Int64 at index [2]

In [29]:
CSV.write("output_csv", df)

"output_csv"

In [30]:
using CSV
using DataFrames

function read_instances_from_txt(filename)
    # Ouvre le fichier et lit chaque ligne (suppose chaque instance est une ligne)
    instances = []
    open(filename, "r") do file
        for line in eachline(file)
            push!(instances, chomp(line))  # Enlève les retours à la ligne
        end
    end
    return instances
end

function generate_csv_from_txt_files(folder_path, output_csv)
    # Crée un DataFrame pour stocker toutes les instances
    df = DataFrame(id = Int[], file = String[], instance = String[])
    
    # Parcourt chaque fichier txt dans le dossier
    txt_files = filter(x -> endswith(x, ".txt"), readdir(folder_path, join=true))
    
    id_counter = 1  # Initialisation d'un compteur d'ID pour chaque instance
    for file in txt_files
        instances = read_instances_from_txt(file)
        for instance in instances
            push!(df, (id_counter, file, instance))
            id_counter += 1
        end
    end
    
    # Sauvegarde toutes les données dans un fichier CSV
    CSV.write(output_csv, df)
end

# Appel de la fonction avec le chemin de votre dossier et le nom de sortie du CSV
generate_csv_from_txt_files("chemin/vers/dossier/txt_files", "instances.csv")

Base.IOError: IOError: readdir("chemin/vers/dossier/txt_files"): no such file or directory (ENOENT)

### Voisinages

In [58]:
assignment

20-element Vector{Int64}:
 3
 1
 1
 2
 5
 2
 3
 2
 5
 3
 2
 4
 4
 4
 1
 3
 5
 4
 1
 5

In [49]:
is_feasible(assignment, "Instances/gap2.txt", 2)

true

In [50]:
is_feasible(swap_tasks(assignment, 1, 2), "Instances/gap2.txt", 2)

false

### Recuit

In [102]:
include("Neighbours.jl")
using Random

function recuit(x0, filename, id, mu, T0, iter_max)

    count = 0

    x_max = copy(x0)
    x = copy(x0)
    T = T0

    while T > 1
        for iter in 1:iter_max
            i = rand(1:m)
            j = rand(1:m)
            while j == i
                j = rand(1:m)
            end
            x_p = swap_tasks(x, i, j)
            
            if is_feasible(x_p, filename, id)
                delta = cal_cost(x_p, filename, id) - cal_cost(x, filename, id)
                if delta > 0 # Maximisation (< 0 pour une minimisation)
                    # println("better")
                    x = copy(x_p)
                    if cal_cost(x, filename, id) > cal_cost(x_max, filename, id)
                        print("better")
                        x_max = copy(x)
                    end
                else
                    q = rand()
                    if q <= exp(-delta/T)
                        x = x_p
                    end
                end
            end
        end
        T = mu * T
        count += 1
        println(T)
    end
    return x
end

recuit (generic function with 2 methods)

In [103]:
x = recuit(assignment, "Instances/gap2.txt", 2, 0.95, 100, 1000)

betterbetterbetter95.0
90.25
85.7375
81.45062499999999
77.37809374999999
73.50918906249998
69.83372960937498
66.34204312890623
63.02494097246091
59.87369392383786
56.880009227645964
54.03600876626366
51.33420832795048
48.76749791155295
46.3291230159753
44.012666865176534
41.812033521917705
39.72143184582182
37.73536025353073
35.84859224085419
34.05616262881148
32.3533544973709
30.735686772502355
29.198902433877237
27.738957312183373
26.352009446574204
25.034408974245494
23.782688525533217
22.593554099256554
21.463876394293724
20.390682574579035
19.371148445850082
18.402591023557576
17.482461472379697
16.60833839876071
15.777921478822675
14.98902540488154
14.239574134637461
13.527595427905588
12.851215656510307
12.208654873684791
11.59822213000055
11.018311023500523
10.467395472325496
9.94402569870922
9.44682441377376
8.97448319308507
8.525759033430816
8.099471081759274
7.69449752767131
7.309772651287744
6.944284018723357
6.5970698177871885
6.267216326897829
5.953855510552938
5.65616273

20-element Vector{Int64}:
 1
 5
 1
 3
 2
 2
 3
 2
 5
 3
 2
 4
 4
 4
 1
 3
 5
 4
 1
 5

In [104]:
is_feasible(x, "Instances/gap2.txt", 2)

true

In [105]:
cal_cost(x, "Instances/gap2.txt", 2)

377

In [106]:
greedy("Instances/gap2.txt", 2)

([3, 1, 1, 2, 5, 2, 3, 2, 5, 3, 2, 4, 4, 4, 1, 3, 5, 4, 1, 5], 358)

In [99]:
cost

358

### Heuristique gloutonne

In [36]:
ratio = c./r

5×15 Matrix{Float64}:
 0.956522  2.1      1.06667   1.30769   …  2.66667  0.6      2.75
 1.35294   1.84615  2.375     0.652174     1.06667  2.3      0.909091
 0.954545  1.17647  0.954545  1.08696      1.0      1.66667  0.6
 3.4       1.10526  1.0       1.5625       1.4      3.125    0.92
 0.681818  2.77778  2.3       0.826087     1.8      2.11111  0.761905

In [37]:
argmax(ratio)

CartesianIndex(2, 10)

In [38]:
current_ressource = zeros(m)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [39]:
current_ressource[1] < b[1]

true

In [40]:
ratio[10,:]

BoundsError: BoundsError: attempt to access 5×15 Matrix{Float64} at index [10, 1:15]

In [41]:
ratio

5×15 Matrix{Float64}:
 0.956522  2.1      1.06667   1.30769   …  2.66667  0.6      2.75
 1.35294   1.84615  2.375     0.652174     1.06667  2.3      0.909091
 0.954545  1.17647  0.954545  1.08696      1.0      1.66667  0.6
 3.4       1.10526  1.0       1.5625       1.4      3.125    0.92
 0.681818  2.77778  2.3       0.826087     1.8      2.11111  0.761905